#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
npx lsc -cbp src/index.ls > dist/index.js
echo "minifying index.js ..."
npx uglifyjs dist/index.js > dist/index.min.js
echo "deploy into local web ..."
rm -rf web/static/assets/lib/wrap-svg-text
mkdir -p web/static/assets/lib/wrap-svg-text/dev
cp -R dist/* web/static/assets/lib/wrap-svg-text/dev
echo "done."

